name: appsehat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.7.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  loading_animation_widget: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bg.png
    - assets/logo.png
    - assets/iklan1.jpg
    - assets/iklan2.jpg
